version: '3.4'

services:

  nginx:
    image: nginx:alpine
    container_name: Nginx
    networks:
      - nginx-net
    volumes:
      - './conf.d:/etc/nginx/conf.d'
    ports:
      - 8080:80
      - 443:443
    restart: always


  Ticketing_API:
    image: dockerreg.shonizcloud.ir/ticketing/api:0.0.7
    container_name: Ticketing_API
    hostname: ticketingapi.shonizcloud.ir
    build:
      context: .
      dockerfile: API/Dockerfile
    networks:
      - dbConnection
      - nginx-net
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Tehran
      - ServiceHost=ticketingapi.shonizcloud.ir
      - Scheme=https
      - ServicePort=443
    depends_on:
      - Ticketing_DB
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


  Ticketing_UI:
    container_name: Ticketing_UI
    hostname: Ticketing_UI
    restart: always
    image: dockerreg.shonizcloud.ir/ticketing/ticketing-ui:0.0.8
    environment:
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Tehran
    networks:
      - nginx-net
    depends_on:
      - Ticketing_API
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


  Ticketing_DB:
    container_name: Ticketing_DB
    hostname: Ticketing_DB
    networks:
      - dbConnection
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123qaz!@#
      - MSSQL_AGENT_ENABLED=True
      - TZ=Asia/Tehran
#    ports:
#      - '8433:1433'
    volumes:
      - 'ticketing-mssql:/var/opt/mssql'
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


volumes:
  ticketing-mssql:
    name: Ticketing-mssql-volume

networks:
  nginx-net:
    external: true
    driver: bridge
  dbConnection:
    external: false
    driver: bridge