//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketContext.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgramResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketContext.Resource.ProgramResource", typeof(ProgramResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف برنامه وجود ندارد..
        /// </summary>
        public static string CannotDeleteProgramException {
            get {
                return ResourceManager.GetString("CannotDeleteProgramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پشتیبان برنامه تکراری است..
        /// </summary>
        public static string DuplicateProgramSupporerIDException {
            get {
                return ResourceManager.GetString("DuplicateProgramSupporerIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان این برنامه نیست..
        /// </summary>
        public static string InvalidProgramSupporterPersonIdException {
            get {
                return ResourceManager.GetString("InvalidProgramSupporterPersonIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام برنامه نمیتواند خالی یا سفید باشد..
        /// </summary>
        public static string NullOrWhiteProgramNameException {
            get {
                return ResourceManager.GetString("NullOrWhiteProgramNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام برنامه تکراری است..
        /// </summary>
        public static string ProgramNameIsDupliateException {
            get {
                return ResourceManager.GetString("ProgramNameIsDupliateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی با این کدپرسنلی تعریف نشده است..
        /// </summary>
        public static string SupporterIdIsNotValidException {
            get {
                return ResourceManager.GetString("SupporterIdIsNotValidException", resourceCulture);
            }
        }
    }
}
