//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketContext.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketContext.Resource.TicketResource", typeof(TicketResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح خطا نمیتواند خالی یا سفید باشد.
        /// </summary>
        public static string ErrorDisctionIsnullOrEmptyException {
            get {
                return ResourceManager.GetString("ErrorDisctionIsnullOrEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع خطا تعریف نشده است..
        /// </summary>
        public static string InvalidErrorTypeExcption {
            get {
                return ResourceManager.GetString("InvalidErrorTypeExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنلی نامعتبر است..
        /// </summary>
        public static string InvalidPersonIDException {
            get {
                return ResourceManager.GetString("InvalidPersonIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه انتخابی تعریف نشده است..
        /// </summary>
        public static string InvalidProgramIDException {
            get {
                return ResourceManager.GetString("InvalidProgramIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدپرسنلی پشتیبان نادرست است..
        /// </summary>
        public static string InvalidSupporterPersonIDException {
            get {
                return ResourceManager.GetString("InvalidSupporterPersonIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این وضعیت تیکت تعریف نشده است..
        /// </summary>
        public static string InvalidTicketConditionExcption {
            get {
                return ResourceManager.GetString("InvalidTicketConditionExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت مورد وجود ندارد..
        /// </summary>
        public static string InvalidTicketIDException {
            get {
                return ResourceManager.GetString("InvalidTicketIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تیکت اشتباه است..
        /// </summary>
        public static string InvalidTicketTypeExcption {
            get {
                return ResourceManager.GetString("InvalidTicketTypeExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنلی نمیتواند خالی یا سفید باشد.
        /// </summary>
        public static string NullOrZiroPersonIDException {
            get {
                return ResourceManager.GetString("NullOrZiroPersonIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح راه حل نیمتواند خالی یا سید باشد..
        /// </summary>
        public static string SolutionDisctionIsnullOrEmptyException {
            get {
                return ResourceManager.GetString("SolutionDisctionIsnullOrEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت تمام شده نمیتوند ویرایش شود..
        /// </summary>
        public static string TheCompetedTicketCannotUpdateEception {
            get {
                return ResourceManager.GetString("TheCompetedTicketCannotUpdateEception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تیکت اشتباه است..
        /// </summary>
        public static string TicketDateTieIsNotValidException {
            get {
                return ResourceManager.GetString("TicketDateTieIsNotValidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت توسط ویرایش کننده ایجاد نشده است..
        /// </summary>
        public static string TicketDidNotCeateByCurrentSupporerException {
            get {
                return ResourceManager.GetString("TicketDidNotCeateByCurrentSupporerException", resourceCulture);
            }
        }
    }
}
